settings delete system pointer_speed
settings delete secure multi_press_timeout
settings delete secure long_press_timeout
settings delete global block_untrusted_touches
settings delete global window_animation_scale
settings delete global transition_animation_scale
settings delete global animator_duration_scale